// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);

		int CountGreater = 0; // מספר הפעמים שהתוצאה גדולה מ-0.5
		int CountLessOrEqual = 0; // מספר הפעמים שהתוצאה קטנה או שווה ל-0.5

		for (int i = 0; i < N; i++) {
		double RandomNum = Math.random();
		  if (RandomNum > 0.5)  {
			CountGreater ++;
		  } else {
			CountLessOrEqual ++;
		}}
		  System.out.println("> 0.5:  " + CountGreater + " times");
		  System.out.println("<= 0.5: " + CountLessOrEqual + " times");

		  if (CountLessOrEqual == 0) {
			System.out.println("Ratio:  undefined (all numbers > 0.5)");

		  }
		  else if (CountGreater == 0) {
			System.out.println("Ratio:  undefined (all numbers <= 0.5)");
		  }

		  else {
			double ratio = (double) CountGreater / CountLessOrEqual;
			System.out.println("Ratio:  " + ratio);

		  }
		
		
	}
}
